name: Deploy to CloudHub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Deploy to CloudHub
        run: mvn deploy
        env:
          muleDeployUser: ${{ secrets.ANYPOINT_USERNAME }}
          muleDeployPassword: ${{ secrets.ANYPOINT_PASSWORD }}
